---
- name: Generate SSH keys
  become: yes
  shell: ssh-keygen -b 2048 -f /home/docker/.ssh/id_rsa -t rsa -q -N "" 
  args:
    creates: /home/docker/.ssh/id_rsa
- name: Copy Public Key Locally
  become: yes
  fetch:
    src: /home/docker/.ssh/id_rsa.pub
    dest: /tmp/
    flat: yes
- name: Copy SSH Configuration
  become: yes
  copy:
    src: ssh_config
    dest: /home/docker/.ssh/config
    mode: 0644
- name: empty known_hosts
  become: yes
  file:
    state: absent
    path: ~/.ssh/known_hosts
- name: run ssh-keyscan to add keys to known_hosts
  become: yes
  shell: "ssh-keyscan {{ item }} >> ~/.ssh/known_hosts"
  with_items:
    - "swarm-manager"
    - "swarm-worker-1"
    - "swarm-worker-2"
